### ISSUE TITLE
[SUGGESTION] allow variable to change walk distance and scan area

### ISSUE THREAD

**Issue by cleftfairy** [timwah/pokeslack#2]
Seems to work quite well!

I have a bike and work in an office. I would love it if i can get notifications for a much wider area and make my own determination if i can get there in time. Also i have nearby friends i can add to slack team. So being able to set these in .env would be great.

**Comment by timwah** [comment]
Adding a configurable NUM_STEPS will be in the next release.

**Comment by timwah** [comment]
Merged to master.
