### ISSUE TITLE
Scan radius has changed from 100m to 70m

### ISSUE THREAD

**Issue by zconnelly13** [timwah/pokeslack#23]
See this reddit post about it: https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/

Does pokeslack take this into account? If not I'm happy to help with the change if someone will point me in the right direction!

**Comment by timwah** [comment]
Thanks for the heads up! Wasn't aware of this. I'll try taking a look myself too, not entirely sure what this changes for us.

**Comment by timwah** [comment]
Thanks @zconnelly13  Please check out PR #26 which should fix this issue. It's merged into master so let me know if you see anymore issues.
